### ISSUE TITLE
Binary for Raspberry Pi

### ISSUE THREAD

**Issue by chrboesch** [kekskurse/go-mail-admin#2]
I created a binary for the Rasperry Pi. Do you want to have it for the releases?

**Comment by kekskurse** [comment]
Yes, that would be great, Pi is a amd64 binary?

**Comment by chrboesch** [comment]
ARM binary. 
[go-mail-admin-with-gui-0.1.2.zip](https://github.com/kekskurse/go-mail-admin/files/4595681/go-mail-admin-with-gui-0.1.2.zip)

**Comment by kekskurse** [comment]
I added also a build step that it create ARM binarys (and also .deb files if it works) to each realease. I still need to test it but from the next version a pi binary should be there.

**Comment by kekskurse** [comment]
I tried the "go-mail-admin-armhf-0.1.3.deb" with the "go-mail-admin-with-gui-linux-arm-0.1.3" binary (will be include in the release) on my pi and it seems to work.
