### ISSUE TITLE
valid spf entry declared as invalid

### ISSUE THREAD

**Issue by gefrit** [kekskurse/go-mail-admin#26]
v=spf1 a:mail.hostname.org mx -all
record == "v=spf1 a:"+d.hostname+" ?all"
perhaps chaging the line into 
strings.Contains(record,"a:"+d.hostname)
would be more generic

**Comment by jamiew0w** [comment]
I'm also seeing this error within the dashboard, everything appears to be setup and working correctly though.

@kekskurse Might be a good idea to link this issue in the readme so new users know it's not an issue with their SPF? Saves you putting out a new release etc.

**Comment by kekskurse** [comment]
hopefully fixed in the next release
