### ISSUE TITLE
Unix socket support for redis

### ISSUE THREAD

**Issue by casswarry0** [kekskurse/go-mail-admin#28]
Would it be possible to support unix sockets for redis?

As far as I can see, in redis.go in line 24 at the redis.Dial("tcp", ...) could you please provide the option to redis.Dial("unix", getConfigVariableWithDefault("REDIS_SOCKET", "/var/run/redis.sock"))?

Or maybe instead of the parameters GOMAILADMIN_REDIS_SERVER and GOMAILADMIN_REDIS_PORT you could make GOMAILADMIN_REDIS_NETWORK (with default "tcp") and GOMAILADMIN_REDIS_ADDRESS (with default "localhost:6379")?

Then line 24 would look like: redis.Dial(getConfigVariableWithDefault("REDIS_NETWORK ", "tcp"), getConfigVariableWithDefault("REDIS_ADDRESS", "localhost:6379"))

So anyone who wants to use unix socket for redis could:
GOMAILADMIN_REDIS_NETWORK=unix
GOMAILADMIN_REDIS_ADDRESS=/path/to/socket

**Comment by kekskurse** [comment]
I added it the way you describe it in the current release 0.2.3.
