### ISSUE TITLE
DKMI (sic) record status within the domain section showing records despite being setup.

### ISSUE THREAD

**Issue by jamiew0w** [kekskurse/go-mail-admin#29]
Hello!

I have DKIM setup for all domains, tested with mxtoolbox and everything looks fine. In the domain section, it's showing as 'no'.

edit; I neglected to check the readme first so that'd be why. Updated config and still showing as 'no' though.

**Comment by jamiew0w** [comment]
Nevermind, I neglected to check the readme first and didn't update the values. Will leave this open until I confirm it's my own fault for being lazy.

**Comment by jamiew0w** [comment]
@kekskurse If possible could you clarify _which_ value is expected by the `GOMAILADMIN_DKIM_VALUE` option please?

For example, the 'tag value' as per mxtoolbox shows mine as `DKIM1` but that's still showing as No, so I'm thinking it must be something else.

Thanks in advance!

**Comment by kekskurse** [comment]
The "complete" DNS Record (with the key). For example i have the following dns record
```
2018._domainkey.kekskurse.io. 3600 IN	TXT	"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1z0thPYq2w43JhirDW+3sQUrf6Hq+cvbdfLyB0KGpCBUwefqJ3OeuLt/WV7SkVMF25OlddZWVZDn1NGFzJ3xRwajfv4kC7taDTtHELPi1bt6MNYQ+K73Yl/QRskNylOya5HSOK7/RlbMEDl4FUAI1e7/84mySt5stuaTAgKzjI5l/P0HUbRYqnBaG/CnIphP2" "epp0NzfJQdfJHReWPXrRSdcnl4Qv9OGNeuSjvP4Ens42xnpmFIaNP3h7CVycXOpl0czQjiWVo3dBziLSL6e6pMioda0/J+2G57C9sLRxqfPAjV7crFnZ8O0csVpbtUZb1rEXXAfrz9SbEZKGyIHVwIDAQAB"
```

for the go-mail-admin config I have

```
GOMAILADMIN_DKIM_SELECTOR="2018"
GOMAILADMIN_DKIM_VALUE="v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1z0thPYq2w43JhirDW+3sQUrf6Hq+cvbdfLyB0KGpCBUwefqJ3OeuLt/WV7SkVMF25OlddZWVZDn1NGFzJ3xRwajfv4kC7taDTtHELPi1bt6MNYQ+K73Yl/QRskNylOya5HSOK7/RlbMEDl4FUAI1e7/84mySt5stuaTAgKzjI5l/P0HUbRYqnBaG/CnIphP2epp0NzfJQdfJHReWPXrRSdcnl4Qv9OGNeuSjvP4Ens42xnpmFIaNP3h7CVycXOpl0czQjiWVo3dBziLSL6e6pMioda0/J+2G57C9sLRxqfPAjV7crFnZ8O0csVpbtUZb1rEXXAfrz9SbEZKGyIHVwIDAQAB"
```

The Check just get all dns keys with the name <GOMAILADMIN_DKIM_SELECTOR>._domainkey.<DOMAIN> and check if one of them is the same as given in <GOMAILADMIN_DKIM_VALUE>.

**Comment by jamiew0w** [comment]
Brilliant, worked first time - excellent update, thanks again @kekskurse!
