### ISSUE TITLE
alias creation page typo

### ISSUE THREAD

**Issue by jakyGIT** [kekskurse/go-mail-admin#34]
Hi!
on the alias creation page there are two rows with "Source Username".
Maybe the lower one should read "Destination Username"?

regards
Juergen

**Comment by kekskurse** [comment]
Hey,

I just have one Source Username on the new Alias page. Is this the page you see this issue?

![2021-06-28_22-5029](https://user-images.githubusercontent.com/1208452/123702457-73bc1500-d863-11eb-95d4-da4a89644239.png)

**Comment by jakyGIT** [comment]
Yes, this is the page. Now that brings me an idea. I Installed the debian package with copy and paste from the installation notes an so I got version 0.1.3..... I will do an update.
Thank you for your support!
Juergen
