### ISSUE TITLE
Cannot set or create anything in GUI

### ISSUE THREAD

**Issue by jakyGIT** [kekskurse/go-mail-admin#35]
Hi,

I cannot create anything (users, aliases, domains) in teheweb-gui. Pressing the save-button just does nothing. I can view all existing users, etc. so the connection to the database seems to be ok. In the system-log-files no error messages are created.
Is there some way to see what is happening?

I tried Chrome and Firefox as browsers.

I installed go-mail-admin via .deb-file on a new debian buster system after following Thomas Leisters guide.

thanx
Juergen

**Comment by kekskurse** [comment]
In the last Version (for Debian 10) the vmail user has just select right in the db. 

The following mysql statments should grant more access to the vmail user or you can create a sperate user with select and insert rights for the gui.

```
grant all on vmail.* to 'vmail'@'localhost' identified by 'yourpass';
FLUSH PRIVILEGES;
```

The gui currently dont show that kind of error, that need to be fixed.

**Comment by jakyGIT** [comment]
Thats it!
I ended up creating an additional user for go-mail-admin. Maybe you want to modify the tutorial so it is independent from the vmail-user. 
Thank you for your support!
Juergen
