### ISSUE TITLE
empty dashboard

### ISSUE THREAD

**Issue by redgloboli** [kekskurse/go-mail-admin#37]
Hi,

i installed the .deb package, added a user with full access to the database, configured the env file but have an empty dashboard.

/var/log/mysql/error.log says:

Aborted connection 23961 to db: 'vmail' user: 'gomail' host: 'localhost' (Got an error reading communication packets).

**Comment by kekskurse** [comment]
Are there any log messages from go-mail-admin after restarting it? You can see them with the following command

```

**Comment by redgloboli** [comment]
ah... yes, it said panic no auth method set (or similar), and it seems i had it written none in lowercase, i changed it to None and now i do get a dashboard.

no software error, human point of failure :)

thanks for getting back to me that quick.
